analyzer:
  plugins:
    - custom_lint

custom_lint:
  debug: true
  verbose: true
  rules:
    - pedant:
      add_class_postfix_by_keyword_list:
        -
          keywordList:
            - final
            - base
          name: Class
      add_class_postfix_by_path_list:
        -
          path: lib/add/
          nameList: 
            - AppBar
            - Button
      add_class_prefix_by_keyword_list:
        -
          keywordList:
            - abstract
            - interface
            - sealed
          name: I
      add_class_prefix_by_path_list:
        -
          path: lib/add/
          nameList: 
            - I