name: pedant
description: A sample command-line application with basic argument parsing.
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_style:
  analyzer: ^6.4.1
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.6.4
