name: pedant
description: A sample command-line application with basic argument parsing.
version: 1.0.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  analyzer: ^6.5.0
  analyzer_plugin: ^0.11.3
  args: ^2.5.0
  custom_lint: ^0.6.4
  custom_lint_builder: ^0.6.4
  path: ^1.9.0
  tint: ^2.0.1
  yaml: ^3.1.2